---
 layout: post  
 categories: Android  
 date:   2016-08-09   
 title: Flask使用记录  
---


## 配置时的一些命令

```
$ git clone https://github.com/miguelgrinberg/flasky.git
$ cd flasky$ git checkout 1a
```

```
$ source venv/bin/activate
```

`deactivate`

---

` (venv) $ pip install flask`

`pip install -r requirements.txt`

`(venv) $ pip freeze >requirements.txt`

----

```
pip install -r requirements.txt
```

`>>> db.create_all()`


`python manage.py db upgrade`


```
(venv) $ python manage.py shell>>> u = User(email='john@example.com', username='john', password='cat')>>> db.session.add(u)>>> db.session.commit()
```

```
(venv) $ python manage.py shell
>>> db.drop_all()
>>> db.create_all()
```


```
(venv) $ python manage.py shell      >>> Role.insert_roles()      >>> Role.query.all()
```

http://www.cnblogs.com/bitCoin/p/5485032.html

<br>

## 一些错误处理

### pip升级库

在 $python manager.py db migrate的时候,
报错版本号不够，可以这样升级库：
 
`sudo pip install --upgrade alembic`
 
### DB Migrate时出错:

> File "/Users/tindle/Company2/board/board/models.py", line 73, in ColumnHas
  created_at = Column(DateTime, nullable=False, default=datetime.now)
TypeError: __init__() got an unexpected keyword argument 'default'

解决：

> DateTime doesn't have a default key as an input. The default key should be an input to the Column function. Try this:

> created_at = Column(DateTime, default=datetime.datetime.utcnow)

> or

> from sqlalchemy.sql import func

> created_at = Column(DateTime(timezone=True), default=func.now())


### 运行时报错：

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

`from datetime import datetime` 改为 `import datetime`

<br>

## 部署到服务器

### virtualenv+supervisor+nginx+gunicorn

http://www.v2ex.com/t/267868

http://www.jikexueyuan.com/course/2060.html

http://www.simpleapples.com/2015/06/configure-nginx-supervisor-gunicorn-flask/

http://codingnow.cn/server/539.html

http://gunicorn.org/

<br>

## Python爬虫

[https://www.zhihu.com/question/20899988](https://www.zhihu.com/question/20899988)
